output_dir: ./output/LongQLoRA-Llama2-7b-8k
model_name_or_path: NousResearch/Llama-2-7b-hf
train_file: ./data/pretrain/pretrain_dummy_data.jsonl
deepspeed: ./train_args/deepspeed/deepspeed_config_s2.json
sft: false

num_train_epochs: 1
max_steps: 1000
per_device_train_batch_size: 1
gradient_accumulation_steps: 16

max_seq_length: 8192
model_max_length: 8192

learning_rate: 0.0002
logging_steps: 50
save_steps: 100
save_total_limit: 3
lr_scheduler_type: constant_with_warmup
warmup_steps: 20

lora_rank: 64
lora_alpha: 16
lora_dropout: 0.05

gradient_checkpointing: true
disable_tqdm: false
optim: paged_adamw_32bit
seed: 42
fp16: true
report_to: tensorboard
dataloader_num_workers: 0
save_strategy: steps
weight_decay: 0
max_grad_norm: 0.3
remove_unused_columns: false